# Generated by Django 5.0.14 on 2025-04-21 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodegas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=50),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articulo',
            name='responsable',
            field=models.CharField(default='No asignado', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ubicacion_actual',
            field=models.CharField(default='Almacén Principal', max_length=200),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
