# Generated by Django 5.0.14 on 2025-04-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodegas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rfid', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_bodegas.articulo')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='gestion_bodegas.bodega')),
                ('bodega_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='gestion_bodegas.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion_bodegas.articulo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion_bodegas.bodega')),
            ],
            options={
                'unique_together': {('bodega', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estanteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='gestion_bodegas.estanteria')),
            ],
            options={
                'unique_together': {('nombre', 'estanteria')},
            },
        ),
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion_bodegas.articulo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion_bodegas.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='gestion_bodegas.bodega')),
            ],
            options={
                'unique_together': {('nombre', 'bodega')},
            },
        ),
        migrations.AddField(
            model_name='estanteria',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='gestion_bodegas.zona'),
        ),
        migrations.DeleteModel(
            name='MovimientoBodega',
        ),
        migrations.AlterUniqueTogether(
            name='estanteria',
            unique_together={('nombre', 'zona')},
        ),
    ]
