# Generated by Django 5.0.14 on 2025-04-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_bodegas', '0002_articulo_estanteria_bodega_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventariobodega',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventariobodega',
            name='estanteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_bodegas.estanteria'),
        ),
        migrations.AddField(
            model_name='inventariobodega',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_bodegas.nivel'),
        ),
        migrations.AddField(
            model_name='inventariobodega',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_bodegas.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariobodega',
            unique_together={('bodega', 'articulo', 'zona', 'estanteria', 'nivel')},
        ),
    ]
